/**
 * AdminLogin.jsx
 *
 * Secure admin login page for the portfolio dashboard.
 *
 * Flow:
 * Admin enters credentials
 *        ↓
 * POST /api/admin/login
 *        ↓
 * Backend validates credentials
 *        ↓
 * JWT generated by backend
 *        ↓
 * JWT stored in HttpOnly cookie
 *        ↓
 * Redirect to Admin Dashboard
 *
 * Notes:
 * - Never log passwords.
 * - JWT is stored in localStorage for this first version.
 * - Protected API requests will use the JWT through adminApi.js.
 */

import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faArrowLeft,
  faEye,
  faEyeSlash,
  faLock,
  faShieldHalved,
  faSpinner,
} from "@fortawesome/free-solid-svg-icons";

/* ============================================================
   API CONFIGURATION
   ============================================================ */

/*
 * Vite environment variable.
 *
 * Local development:
 *
 * VITE_API_URL=http://localhost:5000
 *
 * Production:
 *
 * VITE_API_URL=https://your-backend-domain.com
 */
const API_URL =
  import.meta.env.VITE_API_URL ||
  "http://localhost:5000";

/* ============================================================
   COMPONENT
   ============================================================ */

export default function AdminLogin() {
  const navigate = useNavigate();

  /* ----------------------------------------------------------
     Form state
     ---------------------------------------------------------- */

  const [formData, setFormData] = useState({
    username: "",
    password: "",
  });

  /* ----------------------------------------------------------
     UI state
     ---------------------------------------------------------- */

  const [showPassword, setShowPassword] =
    useState(false);

  const [isLoading, setIsLoading] =
    useState(false);

  const [error, setError] =
    useState("");

  /* ==========================================================
     INPUT HANDLER
     ========================================================== */

  function handleChange(event) {
    const {
      name,
      value,
    } = event.target;

    setFormData((previous) => ({
      ...previous,
      [name]: value,
    }));

    /*
     * Clear an old error as soon as the user starts correcting
     * the form.
     */
    if (error) {
      setError("");
    }
  }

  /* ==========================================================
     FORM SUBMISSION
     ========================================================== */

  /* ==========================================================
   FORM SUBMISSION
   ========================================================== */

async function handleSubmit(event) {
  event.preventDefault();

  /* --------------------------------------------------------
     Basic client-side validation
     -------------------------------------------------------- */

  if (
    !formData.username.trim() ||
    !formData.password
  ) {
    setError(
      "Please enter your username and password."
    );

    return;
  }

  setIsLoading(true);
  setError("");

  try {
    /* ------------------------------------------------------
       Send login request
       ------------------------------------------------------ */

    const response = await fetch(
      `${API_URL}/api/admin/login`,
      {
        method: "POST",

        headers: {
          "Content-Type":
            "application/json",
        },

        /*
         * IMPORTANT:
         *
         * This allows the browser to receive and store
         * the HttpOnly authentication cookie created
         * by the backend.
         */
        credentials: "include",

        body: JSON.stringify({
          username:
            formData.username.trim(),

          password:
            formData.password,
        }),
      }
    );

    /* ------------------------------------------------------
       Parse API response
       ------------------------------------------------------ */

    const data =
      await response.json();

    /* ------------------------------------------------------
       Handle API error
       ------------------------------------------------------ */

    if (
      !response.ok ||
      !data.success
    ) {
      throw new Error(
        data.message ||
          "Unable to sign in."
      );
    }

    /* ------------------------------------------------------
       Store safe admin information
       ------------------------------------------------------ */

    /*
     * We only store non-sensitive administrator information.
     *
     * IMPORTANT:
     *
     * The JWT is NOT stored here.
     *
     * The JWT is already stored by the backend inside
     * the HttpOnly "admin_token" cookie.
     */
    if (data.admin) {
      localStorage.setItem(
        "admin_user",
        JSON.stringify(
          data.admin
        )
      );
    }

    /* ------------------------------------------------------
       Redirect to dashboard
       ------------------------------------------------------ */

    navigate(
      "/admin/dashboard",
      {
        replace: true,
      }
    );
  } catch (requestError) {
    /*
     * Keep technical backend details away from the user.
     */
    setError(
      requestError.message ||
        "Unable to sign in. Please try again."
    );
  } finally {
    setIsLoading(false);
  }
}

  /* ==========================================================
     RENDER
     ========================================================== */

  return (
    <main
      className="
        relative
        flex
        min-h-[100svh]
        items-center
        justify-center
        overflow-hidden
        px-4
        py-8
        sm:px-6
      "
      style={{
        background:
          "var(--page-bg)",
      }}
    >
      {/* ======================================================
          AMBIENT BACKGROUND
          ====================================================== */}

      <div
        aria-hidden="true"
        className="
          pointer-events-none
          absolute
          -right-40
          -top-40
          h-[420px]
          w-[420px]
          rounded-full
          blur-[120px]
        "
        style={{
          background:
            "color-mix(in srgb, var(--accent) 8%, transparent)",
        }}
      />

      <div
        aria-hidden="true"
        className="
          pointer-events-none
          absolute
          -bottom-48
          -left-40
          h-[400px]
          w-[400px]
          rounded-full
          blur-[120px]
        "
        style={{
          background:
            "color-mix(in srgb, var(--accent) 5%, transparent)",
        }}
      />

      {/* ======================================================
          LOGIN CARD
          ====================================================== */}

      <motion.section
        initial={{
          opacity: 0,
          y: 20,
        }}
        animate={{
          opacity: 1,
          y: 0,
        }}
        transition={{
          duration: 0.5,
          ease: [
            0.16,
            1,
            0.3,
            1,
          ],
        }}
        className="
          relative
          z-10
          w-full
          max-w-md
        "
        aria-labelledby="admin-login-title"
      >
        <div
          className="
            rounded-[28px]
            border
            p-6
            shadow-2xl
            backdrop-blur-xl
            sm:p-8
          "
          style={{
            background:
              "color-mix(in srgb, var(--surface-solid) 72%, transparent)",

            borderColor:
              "var(--border)",

            boxShadow:
              "0 24px 80px rgba(0, 0, 0, 0.16)",
          }}
        >
          {/* ==================================================
              TOP BRANDING
              ================================================== */}

          <div className="mb-8">
            <div
              className="
                mb-6
                flex
                items-center
                justify-between
              "
            >
              {/* Logo */}
              <a
                href="/"
                className="
                  font-mono
                  text-lg
                  font-bold
                  tracking-tight
                  outline-none
                  transition-opacity
                  hover:opacity-80
                  focus-visible:ring-2
                  focus-visible:ring-[var(--accent)]
                  focus-visible:ring-offset-2
                "
                style={{
                  color:
                    "var(--text-primary)",
                }}
                aria-label="Return to portfolio home"
              >
                <span
                  style={{
                    color:
                      "var(--accent)",
                  }}
                >
                  &gt;
                </span>{" "}
                SA.
              </a>

              {/* Secure badge */}
              <div
                className="
                  inline-flex
                  items-center
                  gap-2
                  rounded-full
                  px-3
                  py-1.5
                  font-mono
                  text-[9px]
                  font-semibold
                  uppercase
                  tracking-[0.12em]
                "
                style={{
                  color:
                    "var(--accent)",

                  background:
                    "color-mix(in srgb, var(--accent) 8%, transparent)",

                  border:
                    "1px solid color-mix(in srgb, var(--accent) 18%, transparent)",
                }}
              >
                <FontAwesomeIcon
                  icon={faShieldHalved}
                  aria-hidden="true"
                  className="h-2.5 w-2.5"
                />

                Secure
              </div>
            </div>

            {/* Icon */}
            <div
              className="
                mb-5
                flex
                h-12
                w-12
                items-center
                justify-center
                rounded-2xl
              "
              style={{
                background:
                  "color-mix(in srgb, var(--accent) 10%, transparent)",

                border:
                  "1px solid color-mix(in srgb, var(--accent) 18%, transparent)",

                color:
                  "var(--accent)",
              }}
              aria-hidden="true"
            >
              <FontAwesomeIcon
                icon={faLock}
                className="h-5 w-5"
              />
            </div>

            <p
              className="
                mb-2
                font-mono
                text-[10px]
                font-semibold
                uppercase
                tracking-[0.16em]
              "
              style={{
                color:
                  "var(--accent)",
              }}
            >
              Restricted Access
            </p>

            <h1
              id="admin-login-title"
              className="
                font-heading
                text-2xl
                font-bold
                tracking-tight
                sm:text-3xl
              "
              style={{
                color:
                  "var(--text-primary)",
              }}
            >
              Admin login
            </h1>

            <p
              className="
                mt-3
                text-sm
                leading-6
              "
              style={{
                color:
                  "var(--text-secondary)",
              }}
            >
              Sign in to manage your portfolio
              projects and content.
            </p>
          </div>

          {/* ==================================================
              ERROR MESSAGE
              ================================================== */}

          {error && (
            <motion.div
              initial={{
                opacity: 0,
                y: -6,
              }}
              animate={{
                opacity: 1,
                y: 0,
              }}
              role="alert"
              className="
                mb-5
                rounded-xl
                border
                px-4
                py-3
                text-sm
              "
              style={{
                color:
                  "#ef4444",

                background:
                  "color-mix(in srgb, #ef4444 7%, transparent)",

                borderColor:
                  "color-mix(in srgb, #ef4444 20%, transparent)",
              }}
            >
              {error}
            </motion.div>
          )}

          {/* ==================================================
              LOGIN FORM
              ================================================== */}

          <form
            onSubmit={handleSubmit}
            noValidate
          >
            {/* Username */}
            <div className="mb-5">
              <label
                htmlFor="admin-username"
                className="
                  mb-2
                  block
                  text-sm
                  font-semibold
                "
                style={{
                  color:
                    "var(--text-primary)",
                }}
              >
                Username
              </label>

              <input
                id="admin-username"
                name="username"
                type="text"
                value={
                  formData.username
                }
                onChange={handleChange}
                autoComplete="username"
                autoCapitalize="none"
                spellCheck="false"
                disabled={isLoading}
                required
                maxLength={50}
                className="
                  h-12
                  w-full
                  rounded-xl
                  border
                  px-4
                  text-sm
                  outline-none
                  transition-all
                  duration-200
                  disabled:cursor-not-allowed
                  disabled:opacity-60
                  focus:ring-2
                "
                style={{
                  color:
                    "var(--text-primary)",

                  background:
                    "color-mix(in srgb, var(--surface-solid) 55%, transparent)",

                  borderColor:
                    "var(--border)",
                }}
                onFocus={(event) => {
                  event.currentTarget.style.borderColor =
                    "color-mix(in srgb, var(--accent) 55%, transparent)";
                  event.currentTarget.style.boxShadow =
                    "0 0 0 3px color-mix(in srgb, var(--accent) 10%, transparent)";
                }}
                onBlur={(event) => {
                  event.currentTarget.style.borderColor =
                    "var(--border)";
                  event.currentTarget.style.boxShadow =
                    "none";
                }}
              />
            </div>

            {/* Password */}
            <div className="mb-7">
              <label
                htmlFor="admin-password"
                className="
                  mb-2
                  block
                  text-sm
                  font-semibold
                "
                style={{
                  color:
                    "var(--text-primary)",
                }}
              >
                Password
              </label>

              <div className="relative">
                <input
                  id="admin-password"
                  name="password"
                  type={
                    showPassword
                      ? "text"
                      : "password"
                  }
                  value={
                    formData.password
                  }
                  onChange={handleChange}
                  autoComplete="current-password"
                  disabled={isLoading}
                  required
                  className="
                    h-12
                    w-full
                    rounded-xl
                    border
                    px-4
                    pr-12
                    text-sm
                    outline-none
                    transition-all
                    duration-200
                    disabled:cursor-not-allowed
                    disabled:opacity-60
                  "
                  style={{
                    color:
                      "var(--text-primary)",

                    background:
                      "color-mix(in srgb, var(--surface-solid) 55%, transparent)",

                    borderColor:
                      "var(--border)",
                  }}
                  onFocus={(event) => {
                    event.currentTarget.style.borderColor =
                      "color-mix(in srgb, var(--accent) 55%, transparent)";
                    event.currentTarget.style.boxShadow =
                      "0 0 0 3px color-mix(in srgb, var(--accent) 10%, transparent)";
                  }}
                  onBlur={(event) => {
                    event.currentTarget.style.borderColor =
                      "var(--border)";
                    event.currentTarget.style.boxShadow =
                      "none";
                  }}
                />

                <button
                  type="button"
                  onClick={() =>
                    setShowPassword(
                      (previous) =>
                        !previous
                    )
                  }
                  disabled={isLoading}
                  aria-label={
                    showPassword
                      ? "Hide password"
                      : "Show password"
                  }
                  className="
                    absolute
                    right-1
                    top-1
                    flex
                    h-10
                    w-10
                    items-center
                    justify-center
                    rounded-lg
                    outline-none
                    transition-colors
                    hover:bg-black/5
                    dark:hover:bg-white/5
                    focus-visible:ring-2
                    focus-visible:ring-[var(--accent)]
                  "
                  style={{
                    color:
                      "var(--text-muted)",
                  }}
                >
                  <FontAwesomeIcon
                    icon={
                      showPassword
                        ? faEyeSlash
                        : faEye
                    }
                    className="h-4 w-4"
                    aria-hidden="true"
                  />
                </button>
              </div>
            </div>

            {/* Submit */}
            <motion.button
              type="submit"
              disabled={isLoading}
              whileHover={
                !isLoading
                  ? {
                      y: -2,
                    }
                  : undefined
              }
              whileTap={
                !isLoading
                  ? {
                      scale: 0.98,
                    }
                  : undefined
              }
              className="
                flex
                h-12
                w-full
                items-center
                justify-center
                gap-3
                rounded-xl
                px-5
                text-sm
                font-semibold
                text-white
                outline-none
                transition-shadow
                duration-200
                disabled:cursor-not-allowed
                disabled:opacity-70
                focus-visible:ring-2
                focus-visible:ring-[var(--accent)]
                focus-visible:ring-offset-2
              "
              style={{
                background:
                  "var(--accent)",

                boxShadow:
                  "0 8px 24px color-mix(in srgb, var(--accent) 24%, transparent)",
              }}
            >
              {isLoading ? (
                <>
                  <FontAwesomeIcon
                    icon={faSpinner}
                    spin
                    className="h-4 w-4"
                    aria-hidden="true"
                  />

                  Signing in...
                </>
              ) : (
                <>
                  <FontAwesomeIcon
                    icon={faLock}
                    className="h-3.5 w-3.5"
                    aria-hidden="true"
                  />

                  Sign in
                </>
              )}
            </motion.button>
          </form>

          {/* ==================================================
              BACK TO PORTFOLIO
              ================================================== */}

          <button
            type="button"
            onClick={() =>
              navigate("/")
            }
            className="
              mx-auto
              mt-7
              flex
              items-center
              gap-2
              rounded-lg
              px-3
              py-2
              text-xs
              font-medium
              outline-none
              transition-colors
              focus-visible:ring-2
              focus-visible:ring-[var(--accent)]
            "
            style={{
              color:
                "var(--text-muted)",
            }}
          >
            <FontAwesomeIcon
              icon={faArrowLeft}
              className="h-3 w-3"
              aria-hidden="true"
            />

            Back to portfolio
          </button>
        </div>

        {/* ====================================================
            SECURITY NOTE
            ==================================================== */}

        <p
          className="
            mt-5
            text-center
            font-mono
            text-[9px]
            uppercase
            tracking-[0.12em]
          "
          style={{
            color:
              "var(--text-muted)",
          }}
        >
          Protected administrator area
        </p>
      </motion.section>
    </main>
  );
}